ilgi_alanlari = set()

ilgi_alanlari.add("Mobil Uygulama")
ilgi_alanlari.add("Akıllı Sistemler")
ilgi_alanlari.add("Görüntü İşleme")
ilgi_alanlari.add("IHA")
ilgi_alanlari.add("Yapay Sinir Ağları")
ilgi_alanlari.add("Veri Bilimi")
ilgi_alanlari.add("Büyük Veri")
ilgi_alanlari.add("Veri Madenciliği")
ilgi_alanlari.add("Yapay Zeka")
ilgi_alanlari.add("Derin Öğrenme")
ilgi_alanlari.add("Makine Öğrenmesi")
ilgi_alanlari.add("Doğal Dil İşleme")
ilgi_alanlari.add("Bilgisayarlı Görü")
ilgi_alanlari.add("Modern C++")
ilgi_alanlari.add("Kriptoloji")

print(ilgi_alanlari)